## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np


#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
# Copy data set before manipulations
application_df_copy = application_df
application_df_copy = application_df_copy.drop(['EIN', 'NAME'], axis=1)
application_df_copy

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [ ]:
# Confirm columns
application_df_copy.columns

Index(['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE',
       'ORGANIZATION', 'STATUS', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS',
       'ASK_AMT', 'IS_SUCCESSFUL'],
      dtype='object')

In [ ]:
# Determine the number of unique values in each column.
application_df_copy.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
# Counts for each application type: go into df, grab list APPLICATION_TYPE
# and count values for each type
app_type_counts = application_df_copy['APPLICATION_TYPE'].value_counts()
app_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name 'application_types_to_replace`
application_types_to_replace = list(app_type_counts[app_type_counts < 500].index)

# Replace in dataframe
# use for loop and go in the df & grab 'application type' to replace with other
for app in application_types_to_replace:
    application_df_copy['APPLICATION_TYPE'] = application_df_copy['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
# go in the df and give the count of each app type in its bin
application_df_copy['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      804
T8         737
T7         725
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
# go in the df and get the count of each classification
class_count = application_df_copy['CLASSIFICATION'].value_counts()
class_count

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
# go into the first count and get items where count is >1
class_count2 = class_count.loc[class_count > 1]
class_count2.head()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
# go into class count and grab only those less than 1000
classifications_to_replace = list(class_count[class_count < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df_copy['CLASSIFICATION'] = application_df_copy['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df_copy['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_data = pd.get_dummies(application_df_copy)
numeric_data.tail()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
34294,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [ ]:
# Split our preprocessed data into our features and target arrays
# Copy the data first
numeric_data_copy = numeric_data.copy()

# Features
X = numeric_data_copy.drop("IS_SUCCESSFUL", axis=1)
feature_names = X.columns
X.head()

# Labels / Array
y = numeric_data_copy["IS_SUCCESSFUL"].values
y[:100]

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [ ]:
# Counts for y; 0 = No , 1 = Yes
# Confirm the counts
numeric_data["IS_SUCCESSFUL"].value_counts()

1    18261
0    16038
Name: IS_SUCCESSFUL, dtype: int64

In [ ]:
# Confirm the X value dataframe
X.head()

,STATUS,ASK_AMT,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=86)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 50
hidden_nodes_layer2 = 40
hidden_nodes_layer3 = 30

nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu")
)

# Third hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu")
)

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="relu"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_20"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_60 (Dense)            (None, 50)                2150

 dense_61 (Dense)            (None, 40)                2040

 dense_62 (Dense)            (None, 30)                1230

 dense_63 (Dense)            (None, 1)                 31

=================================================================
Total params: 5451 (21.29 KB)
Trainable params: 5451 (21.29 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=15)

Epoch 1/15
804/804 [==============================] - 3s 2ms/step - loss: 0.7145 - accuracy: 0.6937
Epoch 2/15
804/804 [==============================] - 2s 2ms/step - loss: 0.6740 - accuracy: 0.7148
Epoch 3/15
804/804 [==============================] - 1s 2ms/step - loss: 0.6364 - accuracy: 0.7219
Epoch 4/15
804/804 [==============================] - 1s 2ms/step - loss: 0.6339 - accuracy: 0.7211
Epoch 5/15
804/804 [==============================] - 2s 2ms/step - loss: 0.6546 - accuracy: 0.7154
Epoch 6/15
804/804 [==============================] - 2s 2ms/step - loss: 0.6289 - accuracy: 0.7253
Epoch 7/15
804/804 [==============================] - 2s 2ms/step - loss: 0.6267 - accuracy: 0.7270
Epoch 8/15
804/804 [==============================] - 2s 3ms/step - loss: 0.6100 - accuracy: 0.7241
Epoch 9/15
804/804 [==============================] - 2s 2ms/step - loss: 0.5977 - accuracy: 0.7245
Epoch 10/15
804/804 [==============================] - 2s 2ms/step - loss: 0.5972 - accuracy: 0.7244
Epoch 11/15
804/804 [==============================] - 2s 2ms/step - loss: 0.6127 - accuracy: 0.7170
Epoch 12/15
804/804 [==============================] - 2s 2ms/step - loss: 0.5990 - accuracy: 0.7262
Epoch 13/15
804/804 [==============================] - 2s 2ms/step - loss: 0.5997 - accuracy: 0.7253
Epoch 14/15
804/804 [==============================] - 2s 2ms/step - loss: 0.5904 - accuracy: 0.7274
Epoch 15/15
804/804 [==============================] - 2s 3ms/step - loss: 0.5930 - accuracy: 0.7226

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 1.8917 - accuracy: 0.6505 - 768ms/epoch - 3ms/step
Loss: 1.8916765451431274, Accuracy: 0.6504956483840942

In [ ]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE